/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cml_wrapper_MotionSystemWrapper */

#ifndef _Included_com_cml_wrapper_MotionSystemWrapper
#define _Included_com_cml_wrapper_MotionSystemWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cml_wrapper_MotionSystemWrapper
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cml_wrapper_MotionSystemWrapper_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_cml_wrapper_MotionSystemWrapper
 * Method:    homeAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cml_wrapper_MotionSystemWrapper_homeAll
  (JNIEnv *, jobject);

/*
 * Class:     com_cml_wrapper_MotionSystemWrapper
 * Method:    moveTo
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_cml_wrapper_MotionSystemWrapper_moveTo
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
